import { useState, useEffect, useRef, useMemo, useCallback } from "react";
import Head from "next/head";

const C = {
  bg: "#050505", bgAlt: "#0a0a0a", bgCard: "#0e0e0e", bgSidebar: "#080808",
  border: "#1a1a1a", borderHov: "#2e2e2e", borderFocus: "#3a3a3a",
  chrome: "#b8b8b8", chromeBright: "#d8d8d8", chromeDim: "#6a6a6a",
  text: "#e8e8e8", textMid: "#888", textDim: "#4a4a4a",
  success: "#00e676", warn: "#ffab00", error: "#ff5252",
  discord: "#5865F2",
  target: "#cc3333", walmart: "#2d7fd3", pokemonCenter: "#d4a017",
  heroGrad: "linear-gradient(135deg, #0e0e0e 0%, #1a1a1a 30%, #2a2a2a 50%, #1a1a1a 70%, #0e0e0e 100%)",
  heroAccent: "radial-gradient(ellipse at 85% 20%, rgba(200,200,200,0.08) 0%, transparent 60%)",
};
const retailerCol = { Target: C.target, Walmart: C.walmart, "Pokemon Center": C.pokemonCenter, Amazon: "#ff9900", "Best Buy": "#0046be" };
const statusCol = { Delivered: C.success, Shipped: "#4fc3f7", Confirmed: C.warn, Ordered: C.warn, "Out for Delivery": "#7c4dff", "Ready for Pickup": "#7c4dff", Cancelled: C.error, Refunded: C.error, Returned: C.error, "Pre-Order": "#ce93d8", Delayed: C.error, Late: C.error, Substituted: C.warn, "In Transit": "#4fc3f7" };

const I = ({ children, size = 20, ...p }) => (<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" {...p}>{children}</svg>);
const Ico = {
  dashboard: <I><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></I>,
  insights: <I><line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/></I>,
  tracking: <I><path d="M16.5 9.4l-9-5.19"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></I>,
  settings: <I><circle cx="12" cy="12" r="3"/><path d="M12 1v2m0 18v2M4.22 4.22l1.42 1.42m12.72 12.72l1.42 1.42M1 12h2m18 0h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></I>,
  bolt: <I><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></I>,
  discord: <I size={17}><path d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057a.082.082 0 0 0 .031.057 19.9 19.9 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028c.462-.63.874-1.295 1.226-1.994a.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03z" fill="currentColor" stroke="none"/></I>,
  scan: <I><path d="M3 7V5a2 2 0 0 1 2-2h2"/><path d="M17 3h2a2 2 0 0 1 2 2v2"/><path d="M21 17v2a2 2 0 0 1-2 2h-2"/><path d="M7 21H5a2 2 0 0 1-2-2v-2"/><line x1="7" y1="12" x2="17" y2="12"/></I>,
  plus: <I><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></I>,
  trash: <I size={16}><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></I>,
  logout: <I size={16}><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></I>,
  arrow: <I size={14}><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></I>,
  lock: <I size={14}><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></I>,
  trophy: <I><path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6"/><path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18"/><path d="M4 22h16"/><path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 19.24 7 20h10c0-.76-.85-1.25-2.03-1.79C14.47 17.98 14 17.55 14 17v-2.34"/><path d="M18 2H6v7a6 6 0 0 0 12 0V2Z"/></I>,
  terminal: <I><polyline points="4 17 10 11 4 5"/><line x1="12" y1="19" x2="20" y2="19"/></I>,
  pkg: <I><path d="M16.5 9.4l-9-5.19"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></I>,
  cart: <I><circle cx="8" cy="21" r="1"/><circle cx="19" cy="21" r="1"/><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"/></I>,
  gauge: <I><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></I>,
  targetIco: <I><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></I>,
  truck: <I><rect x="1" y="3" width="15" height="13"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></I>,
  extLink: <I size={12}><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></I>,
  copy: <I size={14}><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></I>,
  mail: <I><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></I>,
  calendar: <I><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></I>,
  clock: <I><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></I>,
  edit: <I size={14}><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></I>,
  check: <I size={14}><path d="M20 6L9 17l-5-5"/></I>,
  download: <I size={16}><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></I>,
  refresh: <I size={16}><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/></I>,
  send: <I size={14}><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></I>,
  filter: <I size={16}><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/></I>,
};

/* Shared styles */
const inputBase = { width: "100%", background: C.bgAlt, border: `1px solid ${C.border}`, borderRadius: 8, padding: "12px 14px", color: C.text, fontFamily: "'DM Sans',sans-serif", fontSize: 13, outline: "none", transition: "border-color 0.25s", boxSizing: "border-box" };
const labelBase = { fontFamily: "'DM Sans',sans-serif", fontSize: 10, fontWeight: 600, color: C.textDim, marginBottom: 6, display: "block", letterSpacing: "1px", textTransform: "uppercase" };
const btnPrimary = { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, background: C.text, color: C.bg, fontFamily: "'Syne',sans-serif", fontSize: 13, fontWeight: 700, padding: "11px 24px", borderRadius: 8, border: "none", cursor: "pointer" };
const btnSecondary = { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 6, background: "transparent", color: C.chrome, fontFamily: "'DM Sans',sans-serif", fontSize: 12, fontWeight: 600, padding: "9px 16px", borderRadius: 8, border: `1px solid ${C.border}`, cursor: "pointer" };
const btnGhost = { display: "inline-flex", alignItems: "center", gap: 5, background: "none", border: "none", color: C.textMid, fontFamily: "'DM Sans',sans-serif", fontSize: 12, cursor: "pointer", padding: "6px 10px", borderRadius: 6 };
const tagPill = { display: "inline-flex", alignItems: "center", gap: 6, background: "rgba(200,200,200,0.04)", border: "1px solid rgba(200,200,200,0.08)", borderRadius: 100, padding: "5px 14px", fontFamily: "'DM Sans',sans-serif", fontSize: 11, color: C.chrome, letterSpacing: 1.5, textTransform: "uppercase", fontWeight: 600 };
const focusS = e => { e.target.style.borderColor = C.borderFocus; };
const blurS = e => { e.target.style.borderColor = C.border; };
const cardStyle = { background: C.bgCard, border: `1px solid ${C.border}`, borderRadius: 12, padding: "20px" };
const sectionTitle = { fontFamily: "'Syne',sans-serif", fontSize: 15, fontWeight: 700, color: C.text, marginBottom: 14 };

function Spinner({ size = 28, color = C.chrome }) { return <div style={{ width: size, height: size, border: `2px solid ${C.border}`, borderTopColor: color, borderRadius: "50%", animation: "spin 0.8s linear infinite" }} />; }
function StatusBadge({ status }) { const col = statusCol[status] || C.textMid; return <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, fontWeight: 600, color: col, background: `${col}12`, border: `1px solid ${col}25`, padding: "3px 10px", borderRadius: 5 }}>{status}</span>; }
function RetailerDot({ name, size = 7 }) { return <div style={{ width: size, height: size, borderRadius: "50%", background: retailerCol[name] || C.textDim, flexShrink: 0 }} />; }
function CopyBtn({ text }) { const [copied, setCopied] = useState(false); return <button onClick={e => { e.stopPropagation(); navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); }} style={{ background: "none", border: "none", color: copied ? C.success : C.textDim, cursor: "pointer", padding: 2, display: "flex" }} title="Copy">{copied ? Ico.check : Ico.copy}</button>; }
function EmptyState({ icon, title, desc, action, actionLabel }) { return ( <div style={{ textAlign: "center", padding: "60px 24px" }}><div style={{ width: 64, height: 64, borderRadius: 14, background: "rgba(200,200,200,0.03)", border: `1px solid ${C.border}`, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 20px", color: C.chromeDim }}>{icon}</div><h3 style={{ fontFamily: "'Syne',sans-serif", fontSize: 20, fontWeight: 700, color: C.text, marginBottom: 8 }}>{title}</h3><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 14, color: C.textMid, maxWidth: 360, margin: "0 auto 24px", lineHeight: 1.6 }}>{desc}</p>{action && <button onClick={action} style={btnPrimary}>{actionLabel}</button>}</div> ); }
function Reveal({ children, delay = 0, style = {} }) { const ref = useRef(null); const [vis, setVis] = useState(false); useEffect(() => { if (!ref.current) return; const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) { setVis(true); obs.disconnect(); } }, { threshold: 0.15 }); obs.observe(ref.current); return () => obs.disconnect(); }, []); return <div ref={ref} style={{ ...style, opacity: vis ? 1 : 0, transform: vis ? "translateY(0)" : "translateY(16px)", transition: `opacity 0.5s ease ${delay}s, transform 0.5s ease ${delay}s` }}>{children}</div>; }

function trackingUrl(carrier, number) { if (!carrier || !number) return null; const c = carrier.toLowerCase(); if (c === "ups") return `https://www.ups.com/track?tracknum=${number}`; if (c === "usps") return `https://tools.usps.com/go/TrackConfirmAction?tLabels=${number}`; if (c === "fedex") return `https://www.fedex.com/fedextrack/?trknbr=${number}`; if (c === "ontrac") return `https://www.ontrac.com/tracking/?number=${number}`; if (c === "lasership" || c === "laser ship") return `https://www.lasership.com/track/${number}`; if (c === "dhl") return `https://www.dhl.com/us-en/home/tracking.html?tracking-id=${number}`; return null; }

/* Hero Banner */
function HeroBanner({ children }) {
  return (<div style={{ position: "relative", background: C.heroGrad, border: `1px solid ${C.border}`, borderRadius: 14, padding: "28px 32px", marginBottom: 24, overflow: "hidden" }}><div style={{ position: "absolute", inset: 0, background: C.heroAccent, pointerEvents: "none" }}/><div style={{ position: "absolute", top: -40, right: -20, width: 200, height: 300, background: "linear-gradient(160deg, transparent 40%, rgba(184,184,184,0.03) 50%, transparent 60%)", transform: "rotate(-15deg)", pointerEvents: "none" }}/><div style={{ position: "relative", zIndex: 1 }}>{children}</div></div>);
}

/* Sparkline */
function Sparkline({ data = [], color = C.chrome, width = 120, height = 32 }) {
  if (!data.length) return null;
  const min = Math.min(...data); const max = Math.max(...data); const range = max - min || 1;
  const points = data.map((v, i) => { const x = (i / (data.length - 1)) * width; const y = height - ((v - min) / range) * (height - 4) - 2; return `${x},${y}`; }).join(" ");
  return (<svg width={width} height={height} style={{ display: "block", marginTop: 8, opacity: 0.6 }}><polyline points={points} fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>);
}

/* Donut Chart */
function DonutChart({ data, size = 140 }) {
  const total = data.reduce((s, d) => s + d.value, 0); if (!total) return null;
  const r = size / 2 - 8; const cx = size / 2; const cy = size / 2; const circ = 2 * Math.PI * r; let offset = 0;
  return (<svg width={size} height={size} style={{ display: "block" }}>{data.map((d, i) => { const pct = d.value / total; const dash = pct * circ; const gap = circ - dash; const o = offset; offset += dash; return <circle key={i} cx={cx} cy={cy} r={r} fill="none" stroke={d.color} strokeWidth="18" strokeDasharray={`${dash} ${gap}`} strokeDashoffset={-o} transform={`rotate(-90 ${cx} ${cy})`}/>; })}<text x={cx} y={cy - 6} textAnchor="middle" fill={C.text} fontFamily="'Bebas Neue',sans-serif" fontSize="26" letterSpacing="1">{total}</text><text x={cx} y={cy + 12} textAnchor="middle" fill={C.textDim} fontFamily="'DM Mono',monospace" fontSize="8" letterSpacing="1">ORDERS</text></svg>);
}

/* Shipping Progress Dots */
function ShippingProgress({ status }) {
  const steps = ["Ordered","Shipped","In Transit","Out for Delivery","Delivered"];
  const statusMap = { Confirmed: 0, Ordered: 0, "Pre-Order": 0, Shipped: 1, "In Transit": 2, "Out for Delivery": 3, Delivered: 4, Cancelled: -1, Refunded: -1, Returned: -1, Late: 2, Delayed: 1 };
  const current = statusMap[status] ?? 0; if (current < 0) return <StatusBadge status={status} />;
  return (<div style={{ display: "flex", alignItems: "center", gap: 3 }}>{steps.map((_, i) => { const filled = i <= current; const active = i === current; return <div key={i} style={{ width: active ? 18 : 10, height: 6, borderRadius: 3, background: filled ? (i === 4 ? C.success : "#4fc3f7") : "rgba(200,200,200,0.08)" }}/>; })}</div>);
}

/* Time Range Filter */
function TimeRangeFilter({ value, onChange }) {
  const ranges = [{ key: "7d", label: "7D" },{ key: "30d", label: "30D" },{ key: "90d", label: "90D" },{ key: "ytd", label: "YTD" },{ key: "1y", label: "1Y" },{ key: "all", label: "All" }];
  return (<div style={{ display: "flex", gap: 2, background: "rgba(200,200,200,0.03)", borderRadius: 8, padding: 3 }}>{ranges.map(r => (<button key={r.key} onClick={() => onChange(r.key)} style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, fontWeight: value === r.key ? 700 : 400, color: value === r.key ? C.text : C.textDim, background: value === r.key ? "rgba(200,200,200,0.08)" : "transparent", border: "none", borderRadius: 6, padding: "6px 12px", cursor: "pointer" }}>{r.label}</button>))}</div>);
}

/* CSV Export */
function exportCSV(orders) {
  const headers = ["Order Date","Retailer","Item","Order Number","Status","Carrier","Tracking Number","Total","Subtotal","Tax","Shipped Date","Delivered Date","Estimated Delivery"];
  const rows = orders.map(o => [o.order_date||"",o.retailer||"",`"${(o.item||"").replace(/"/g,'""')}"`,o.order_number||"",o.status||"",o.carrier||"",o.tracking_number||"",o.total||"",o.subtotal||"",o.tax||"",o.shipped_date||"",o.delivered_date||"",o.estimated_delivery||""]);
  const csv = [headers.join(","), ...rows.map(r => r.join(","))].join("\n");
  const blob = new Blob([csv], { type: "text/csv" }); const url = URL.createObjectURL(blob);
  const a = document.createElement("a"); a.href = url; a.download = `livefast-orders-${new Date().toISOString().split("T")[0]}.csv`; a.click(); URL.revokeObjectURL(url);
}

/* ═══════════════════════════════════════════════════════════════
   LANDING PAGE
   ═══════════════════════════════════════════════════════════════ */
const checkoutItems = [
  { product: "Prismatic Evolutions ETB", retailer: "Target", price: "$54.99" },
  { product: "Surging Sparks Booster Bundle", retailer: "Walmart", price: "$29.97" },
  { product: "Charizard ex Premium Collection", retailer: "Pokemon Center", price: "$39.99" },
  { product: "151 Ultra Premium Collection", retailer: "Target", price: "$119.99" },
  { product: "Paldean Fates ETB", retailer: "Walmart", price: "$49.99" },
  { product: "Twilight Masquerade BB", retailer: "Pokemon Center", price: "$89.99" },
  { product: "Crown Zenith ETB", retailer: "Target", price: "$44.99" },
  { product: "Scarlet & Violet ETB", retailer: "Walmart", price: "$39.99" },
];
const memberTags = ["JK","DR","MT","AL","SB","RC","NW","TH","KP","MG"];

function LiveTerminal() {
  const [lines, setLines] = useState([]);
  useEffect(() => { const seed = []; for (let i = 0; i < 6; i++) { const item = checkoutItems[Math.floor(Math.random() * checkoutItems.length)]; seed.push({ ...item, member: memberTags[Math.floor(Math.random() * memberTags.length)], time: `${Math.floor(Math.random() * 30) + 1}m ago`, id: i }); } setLines(seed); const iv = setInterval(() => { const item = checkoutItems[Math.floor(Math.random() * checkoutItems.length)]; setLines(p => [{ ...item, member: memberTags[Math.floor(Math.random() * memberTags.length)], time: "just now", id: Date.now() }, ...p.slice(0, 7)]); }, 3200); return () => clearInterval(iv); }, []);
  return (
    <div style={{ background: C.bg, border: `1px solid ${C.border}`, borderRadius: 12, overflow: "hidden", position: "relative" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 18px", borderBottom: `1px solid ${C.border}`, background: "rgba(255,255,255,0.01)" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ display: "flex", gap: 6 }}><div style={{ width: 10, height: 10, borderRadius: "50%", background: "#ff5f56" }}/><div style={{ width: 10, height: 10, borderRadius: "50%", background: "#ffbd2e" }}/><div style={{ width: 10, height: 10, borderRadius: "50%", background: "#27c93f" }}/></div><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim, marginLeft: 8 }}>livefast-checkout-feed</span></div>
        <div style={{ display: "flex", alignItems: "center", gap: 6 }}><div style={{ width: 6, height: 6, borderRadius: "50%", background: C.success, animation: "pulse 2s ease infinite" }}/><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.success, letterSpacing: 1 }}>LIVE</span></div>
      </div>
      <div style={{ padding: "8px 0", maxHeight: 280, overflow: "hidden" }}>
        {lines.map((l, i) => (<div key={l.id} style={{ display: "flex", alignItems: "center", gap: 12, padding: "8px 18px", opacity: 1 - i * 0.1, animation: i === 0 ? "slideIn 0.4s ease" : "none" }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, minWidth: 48, flexShrink: 0 }}>{l.time}</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.success, flexShrink: 0 }}>CHECKOUT</span><div style={{ width: 22, height: 22, borderRadius: 5, background: "rgba(200,200,200,0.06)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 8, color: C.chrome, fontWeight: 700 }}>{l.member}</span></div><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.text, flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{l.product}</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: retailerCol[l.retailer] || C.textMid, flexShrink: 0, textTransform: "uppercase", letterSpacing: 0.5 }}>{l.retailer}</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.chrome, fontWeight: 600, flexShrink: 0 }}>{l.price}</span></div>))}
      </div>
      <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: 50, background: `linear-gradient(transparent, ${C.bg})`, pointerEvents: "none" }}/>
    </div>
  );
}

function LandingPage({ error }) {
  const AUTH_ERRORS = { access_denied: "Login was cancelled.", not_in_server: "You need to be in the LIVEFAST Discord.", missing_role: "You haven't been verified yet. Complete verification in Discord.", auth_failed: "Something went wrong. Please try again." };
  const errorMsg = error ? AUTH_ERRORS[error] || AUTH_ERRORS.auth_failed : null;
  return (
    <div style={{ minHeight: "100vh", background: C.bg }}>
      <nav style={{ position: "fixed", top: 0, left: 0, right: 0, zIndex: 1000, background: "rgba(5,5,5,0.7)", backdropFilter: "blur(24px)", borderBottom: `1px solid ${C.border}` }}><div style={{ maxWidth: 1140, margin: "0 auto", padding: "0 24px", display: "flex", alignItems: "center", justifyContent: "space-between", height: 56 }}><div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ width: 32, height: 32, borderRadius: 7, border: `1.5px solid ${C.border}`, background: C.bg, display: "flex", alignItems: "center", justifyContent: "center" }}><span style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 14, color: C.chromeBright, letterSpacing: 1 }}>LF</span></div><div><span style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 16, color: C.text, letterSpacing: 2.5, display: "block", lineHeight: 1 }}>LIVEFAST</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 7, color: C.textDim, letterSpacing: 3 }}>ACO SYSTEMS</span></div></div><a href="/api/auth/login" style={{ ...btnPrimary, fontSize: 12, padding: "8px 18px", textDecoration: "none", gap: 6 }}>{Ico.discord} Sign In</a></div></nav>
      <section style={{ position: "relative", paddingTop: 56, overflow: "hidden" }}>
        <div style={{ position: "absolute", top: -300, left: "50%", transform: "translateX(-50%)", width: 1000, height: 1000, background: "radial-gradient(circle, rgba(180,180,180,0.04) 0%, transparent 65%)", pointerEvents: "none" }}/>
        <div style={{ maxWidth: 860, margin: "0 auto", padding: "72px 24px 48px", textAlign: "center", position: "relative" }}>
          <Reveal><div style={{ display: "flex", justifyContent: "center" }}><div style={tagPill}>{Ico.bolt} Automated Checkout Operations</div></div></Reveal>
          <Reveal delay={0.08}><h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "clamp(52px, 10vw, 110px)", lineHeight: 0.95, color: C.text, margin: "28px 0 0", letterSpacing: 2 }}>SCORE THE</h1><h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "clamp(52px, 10vw, 110px)", lineHeight: 0.95, letterSpacing: 2, margin: "0 0 28px", background: `linear-gradient(135deg, ${C.chromeBright} 0%, ${C.chromeDim} 40%, ${C.chromeBright} 60%, ${C.chromeDim} 100%)`, backgroundSize: "200% 100%", animation: "shimmer 4s ease infinite", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>UNOBTAINABLE.</h1></Reveal>
          <Reveal delay={0.16}><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: "clamp(15px, 2vw, 17px)", color: C.textMid, lineHeight: 1.75, maxWidth: 520, margin: "0 auto 40px" }}>Your one-stop shop for automated checkouts across Target, Walmart, and Pokemon Center. We handle the speed. You get the product.</p></Reveal>
          <Reveal delay={0.24}>{errorMsg && <div style={{ maxWidth: 420, margin: "0 auto 20px", padding: "12px 16px", background: "rgba(255,80,80,0.06)", border: "1px solid rgba(255,80,80,0.15)", borderRadius: 8 }}><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: "#ff6b6b" }}>{errorMsg}</p></div>}<a href="/api/auth/login" style={{ ...btnPrimary, padding: "14px 32px", fontSize: 14, textDecoration: "none", boxShadow: "0 0 40px rgba(200,200,200,0.08)" }}>{Ico.discord} Sign in with Discord {Ico.arrow}</a><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.textDim, marginTop: 12 }}>Not a member? <a href="https://discord.gg/livefast" target="_blank" rel="noopener noreferrer" style={{ color: C.discord, textDecoration: "none", fontWeight: 600 }}>Join our Discord</a></p></Reveal>
        </div>
        <Reveal delay={0.32}><div style={{ maxWidth: 780, margin: "0 auto 60px", padding: "0 24px" }}><LiveTerminal /></div></Reveal>
      </section>
      <section style={{ maxWidth: 960, margin: "0 auto", padding: "40px 24px 80px" }}><Reveal><div style={{ textAlign: "center", marginBottom: 48 }}><div style={{ display: "flex", justifyContent: "center" }}><div style={tagPill}>{Ico.terminal} How It Works</div></div><h2 style={{ fontFamily: "'Syne',sans-serif", fontSize: "clamp(26px, 4vw, 36px)", fontWeight: 800, color: C.text, marginTop: 20 }}>Three steps to get started.</h2></div></Reveal><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: 1, background: C.border, borderRadius: 14, overflow: "hidden" }}>{[{ num: "01", title: "Join & Connect", desc: "Hop into the LIVEFAST Discord, verify your account, and connect your profile.", icon: Ico.discord },{ num: "02", title: "Pick Your Targets", desc: "Select your retailers, choose the products you want to secure, and get set up.", icon: Ico.targetIco },{ num: "03", title: "We Handle the Rest", desc: "Our systems run the moment products go live. You get notified when we land a checkout.", icon: Ico.bolt }].map((s, i) => (<Reveal key={i} delay={i * 0.1}><div style={{ background: C.bgCard, padding: "32px 24px", height: "100%" }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}><span style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 36, color: "rgba(200,200,200,0.06)", letterSpacing: 2 }}>{s.num}</span><div style={{ color: C.chromeDim }}>{s.icon}</div></div><h3 style={{ fontFamily: "'Syne',sans-serif", fontSize: 17, fontWeight: 700, color: C.text, marginBottom: 8 }}>{s.title}</h3><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.textMid, lineHeight: 1.7 }}>{s.desc}</p></div></Reveal>))}</div></section>
      <section style={{ background: C.bgAlt, padding: "80px 24px", borderTop: `1px solid ${C.border}`, borderBottom: `1px solid ${C.border}` }}><div style={{ maxWidth: 960, margin: "0 auto" }}><Reveal><div style={tagPill}>{Ico.pkg} What We Offer</div><h2 style={{ fontFamily: "'Syne',sans-serif", fontSize: "clamp(26px, 4vw, 36px)", fontWeight: 800, color: C.text, marginTop: 20, marginBottom: 40 }}>Everything you need, nothing you don{"'"}t.</h2></Reveal><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 12 }}>{[{ icon: Ico.trophy, title: "Pay Per Success", desc: "No monthly fees. You only pay after we land a checkout." },{ icon: Ico.cart, title: "Multi-Retailer ACO", desc: "Automated checkouts across Target, Walmart, and Pokemon Center." },{ icon: Ico.scan, title: "Email Order Scraper", desc: "Connect your email and we pull every order confirmation and tracking update." },{ icon: Ico.gauge, title: "Live Order Tracking", desc: "Real-time status updates, carrier tracking, and spend history." }].map((s, i) => (<Reveal key={i} delay={i * 0.06}><div style={{ ...cardStyle, height: "100%" }}><div style={{ color: C.chromeDim, marginBottom: 14 }}>{s.icon}</div><h3 style={{ fontFamily: "'Syne',sans-serif", fontSize: 16, fontWeight: 700, color: C.text, marginBottom: 8 }}>{s.title}</h3><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.textMid, lineHeight: 1.7 }}>{s.desc}</p></div></Reveal>))}</div></div></section>
      <section style={{ padding: "80px 24px" }}><Reveal><div style={{ maxWidth: 500, margin: "0 auto", textAlign: "center" }}><h2 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: "clamp(36px, 6vw, 52px)", color: C.text, letterSpacing: 2, lineHeight: 1 }}>READY TO GET STARTED?</h2><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 15, color: C.textMid, margin: "16px 0 28px", lineHeight: 1.7 }}>Join the LIVEFAST community and start securing products today.</p><a href="/api/auth/login" style={{ ...btnPrimary, padding: "14px 32px", textDecoration: "none" }}>{Ico.discord} Sign in with Discord</a></div></Reveal></section>
      <footer style={{ borderTop: `1px solid ${C.border}`, padding: "32px 24px" }}><div style={{ maxWidth: 960, margin: "0 auto", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 12 }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><div style={{ width: 24, height: 24, borderRadius: 5, border: `1px solid ${C.border}`, display: "flex", alignItems: "center", justifyContent: "center" }}><span style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 10, color: C.chrome }}>LF</span></div><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim }}>&copy; 2026 LIVEFAST LLC</span></div><div style={{ display: "flex", gap: 20 }}><a href="https://discord.gg/livefast" target="_blank" rel="noopener noreferrer" style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.textDim, textDecoration: "none" }}>Discord</a><a href="https://twitter.com/livefastaco" target="_blank" rel="noopener noreferrer" style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.textDim, textDecoration: "none" }}>Twitter / X</a></div></div></footer>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   SIDEBAR
   ═══════════════════════════════════════════════════════════════ */
function Sidebar({ page, setPage, user, collapsed, setCollapsed, inTransitCount }) {
  const navItems = [{ id: "dashboard", label: "Dashboard", icon: Ico.dashboard },{ id: "tracking", label: "Tracking", icon: Ico.tracking, badge: inTransitCount },{ id: "drops", label: "Upcoming Drops", icon: Ico.calendar },{ id: "emails", label: "Accounts", icon: Ico.mail },{ id: "insights", label: "Insights", icon: Ico.insights },{ id: "settings", label: "Settings", icon: Ico.settings }];
  const w = collapsed ? 64 : 220;
  return (
    <aside style={{ width: w, minHeight: "100vh", background: C.bgSidebar, borderRight: `1px solid ${C.border}`, position: "fixed", top: 0, left: 0, zIndex: 1000, display: "flex", flexDirection: "column", transition: "width 0.25s ease", overflow: "hidden" }}>
      <div style={{ padding: collapsed ? "18px 0" : "18px 16px", display: "flex", alignItems: "center", gap: 10, borderBottom: `1px solid ${C.border}`, justifyContent: collapsed ? "center" : "flex-start", minHeight: 60 }}><div style={{ width: 30, height: 30, borderRadius: 7, border: `1.5px solid ${C.border}`, background: C.bg, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, cursor: "pointer" }} onClick={() => setCollapsed(!collapsed)}><span style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 13, color: C.chromeBright, letterSpacing: 1 }}>LF</span></div>{!collapsed && <div><span style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 15, color: C.text, letterSpacing: 2, display: "block", lineHeight: 1 }}>LIVEFAST</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 7, color: C.textDim, letterSpacing: 2.5 }}>ACO SYSTEMS</span></div>}</div>
      <nav style={{ flex: 1, padding: "12px 8px", display: "flex", flexDirection: "column", gap: 2 }}>{navItems.map(n => { const active = page === n.id; return (<button key={n.id} onClick={() => setPage(n.id)} title={collapsed ? n.label : undefined} style={{ display: "flex", alignItems: "center", gap: 12, width: "100%", background: active ? "rgba(200,200,200,0.06)" : "transparent", border: "none", borderRadius: 8, padding: collapsed ? "11px 0" : "11px 14px", cursor: "pointer", justifyContent: collapsed ? "center" : "flex-start" }} onMouseEnter={e => { if (!active) e.currentTarget.style.background = "rgba(200,200,200,0.03)"; }} onMouseLeave={e => { e.currentTarget.style.background = active ? "rgba(200,200,200,0.06)" : "transparent"; }}><div style={{ color: active ? C.text : C.chromeDim, flexShrink: 0, position: "relative" }}>{n.icon}{n.badge > 0 && collapsed && <div style={{ position: "absolute", top: -4, right: -4, width: 14, height: 14, borderRadius: "50%", background: "#4fc3f7", display: "flex", alignItems: "center", justifyContent: "center" }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 8, color: C.bg, fontWeight: 700 }}>{n.badge}</span></div>}</div>{!collapsed && <span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, fontWeight: active ? 600 : 400, color: active ? C.text : C.textMid, whiteSpace: "nowrap", flex: 1, textAlign: "left" }}>{n.label}</span>}{!collapsed && n.badge > 0 && <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: "#4fc3f7", background: "rgba(79,195,247,0.1)", padding: "2px 7px", borderRadius: 4, fontWeight: 700 }}>{n.badge}</span>}</button>); })}</nav>
      <div style={{ padding: collapsed ? "12px 8px" : "12px 16px", borderTop: `1px solid ${C.border}` }}><div style={{ display: "flex", alignItems: "center", gap: 10, justifyContent: collapsed ? "center" : "flex-start" }}><div style={{ width: 28, height: 28, borderRadius: 7, background: "rgba(88,101,242,0.15)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.discord, fontWeight: 700 }}>{user?.username?.charAt(0)?.toUpperCase() || "?"}</span></div>{!collapsed && <><div style={{ flex: 1, minWidth: 0 }}><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.text, fontWeight: 500, display: "block", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{user?.username || "Member"}</span></div><a href="/api/auth/logout" title="Sign out" style={{ color: C.textDim, display: "flex", textDecoration: "none" }}>{Ico.logout}</a></>}</div></div>
    </aside>
  );
}

/* ═══════════════════════════════════════════════════════════════
   DASHBOARD PAGE
   ═══════════════════════════════════════════════════════════════ */
function DashboardPage({ setPage, data, loading, runScan, scanning, scanResult, setScanResult }) {
  const [timeRange, setTimeRange] = useState("all");
  if (loading) return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "60vh" }}><Spinner /></div>;
  if (!data?.stats?.totalOrders) return <EmptyState icon={Ico.pkg} title="No orders yet" desc="Link an email account in the Accounts tab, then run your first scan." action={() => setPage("emails")} actionLabel="Link Email Account" />;
  const { stats, orders, activeShipments, allOrders } = data;
  const retailers = Object.keys(stats.byRetailer);
  const spendByDay = useMemo(() => { if (!allOrders) return []; const days = {}; allOrders.forEach(o => { if (o.order_date && o.total) { days[o.order_date] = (days[o.order_date] || 0) + Number(o.total); } }); return Object.values(days).slice(-14); }, [allOrders]);
  const ordersByDay = useMemo(() => { if (!allOrders) return []; const days = {}; allOrders.forEach(o => { if (o.order_date) { days[o.order_date] = (days[o.order_date] || 0) + 1; } }); return Object.values(days).slice(-14); }, [allOrders]);
  const biggestDay = useMemo(() => { if (!allOrders) return { amount: 0, date: "" }; const days = {}; allOrders.forEach(o => { if (o.order_date && o.total) { days[o.order_date] = (days[o.order_date] || 0) + Number(o.total); } }); let max = 0, maxDate = ""; Object.entries(days).forEach(([d, v]) => { if (v > max) { max = v; maxDate = d; } }); return { amount: max, date: maxDate }; }, [allOrders]);
  const topProducts = data.topProducts?.slice(0, 5) || [];
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 12, marginBottom: 20 }}><div><h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, letterSpacing: 3 }}>DASHBOARD</h1><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>{stats.totalOrders} orders tracked &middot; {stats.withTracking || 0} with tracking</p></div><button onClick={runScan} disabled={scanning} style={{ ...btnPrimary, fontSize: 12, padding: "9px 16px", opacity: scanning ? 0.6 : 1 }}>{scanning ? <Spinner size={14} color={C.bg}/> : Ico.scan} {scanning ? "Scanning..." : "Run Scan"}</button></div>
      {scanResult && (<div style={{ marginBottom: 16, padding: "12px 16px", background: scanResult.error ? "rgba(255,80,80,0.05)" : "rgba(0,230,118,0.05)", border: `1px solid ${scanResult.error ? "rgba(255,80,80,0.12)" : "rgba(0,230,118,0.12)"}`, borderRadius: 8, display: "flex", justifyContent: "space-between", alignItems: "center" }}><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: scanResult.error ? "#ff6b6b" : C.success }}>{scanResult.error || `Scan complete: ${scanResult.count} orders found, ${scanResult.updated || 0} updated.`}</p><button onClick={() => setScanResult(null)} style={{ background: "none", border: "none", color: C.textDim, cursor: "pointer", fontSize: 18 }}>&times;</button></div>)}
      {/* Hero banner */}
      <HeroBanner><div style={{ display: "grid", gridTemplateColumns: "1.4fr 1fr 1fr 1fr", gap: 20, alignItems: "center" }}><div><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 6 }}>Total Spend</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 48, color: C.text, letterSpacing: 2, lineHeight: 1 }}>${Number(stats.totalSpend).toLocaleString(undefined, { minimumFractionDigits: 2 })}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim, marginTop: 4 }}>{stats.totalOrders} orders &middot; avg ${stats.avgOrderValue}</p></div><div style={{ borderLeft: `1px solid ${C.border}`, paddingLeft: 20 }}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 6 }}>Orders</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, lineHeight: 1 }}>{stats.totalOrders}</p></div><div style={{ borderLeft: `1px solid ${C.border}`, paddingLeft: 20 }}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 6 }}>Fulfillment</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.success, lineHeight: 1 }}>{stats.fulfillmentRate}%</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginTop: 2 }}>{stats.delivered} delivered</p></div><div style={{ borderLeft: `1px solid ${C.border}`, paddingLeft: 20 }}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 6 }}>In Transit</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: "#4fc3f7", lineHeight: 1 }}>{(stats.byStatus?.Shipped || 0) + (stats.byStatus?.["Out for Delivery"] || 0)}</p></div></div></HeroBanner>
      <div style={{ marginBottom: 20 }}><TimeRangeFilter value={timeRange} onChange={setTimeRange} /></div>
      {/* Stat cards with sparklines */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12, marginBottom: 24 }}>
        <div style={cardStyle}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 4 }}>Active</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, lineHeight: 1 }}>{(stats.byStatus?.Confirmed || 0) + (stats.byStatus?.Shipped || 0) + (stats.byStatus?.["Out for Delivery"] || 0)}</p><Sparkline data={ordersByDay} color={C.chrome} /></div>
        <div style={cardStyle}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 4 }}>Delivered</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.success, lineHeight: 1 }}>{stats.delivered || 0}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginTop: 4 }}>{stats.byStatus?.Shipped || 0} shipped</p></div>
        <div style={cardStyle}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 4 }}>Cancelled</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.error, lineHeight: 1 }}>{(stats.byStatus?.Cancelled || 0) + (stats.byStatus?.Refunded || 0)}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginTop: 4 }}>{stats.totalOrders > 0 ? Math.round(((stats.byStatus?.Cancelled || 0) / stats.totalOrders) * 100) : 0}% of orders</p></div>
        <div style={cardStyle}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 4 }}>Biggest Day</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, lineHeight: 1 }}>${biggestDay.amount.toFixed(2)}</p>{biggestDay.date && <p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginTop: 4 }}>{new Date(biggestDay.date + "T12:00:00").toLocaleDateString("en-US", { month: "short", day: "numeric" })}</p>}<Sparkline data={spendByDay} color={C.warn} /></div>
      </div>
      {/* Top Products */}
      {topProducts.length > 0 && (<div style={{ marginBottom: 24 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 }}><h3 style={{ ...sectionTitle, marginBottom: 0, display: "flex", alignItems: "center", gap: 8 }}>{Ico.trophy} Top Products</h3><button onClick={() => setPage("insights")} style={btnGhost}>View all {Ico.arrow}</button></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 }}>{topProducts.map((p, i) => (<div key={i} style={{ ...cardStyle, padding: "16px", position: "relative" }}><div style={{ position: "absolute", top: 10, left: 12 }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, fontWeight: 700, color: i < 3 ? C.warn : C.textDim, background: i < 3 ? "rgba(255,171,0,0.1)" : "rgba(200,200,200,0.04)", padding: "2px 8px", borderRadius: 4 }}>#{i + 1}</span></div><div style={{ paddingTop: 20 }}><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.text, fontWeight: 600, lineHeight: 1.4, marginBottom: 8, minHeight: 34, overflow: "hidden", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical" }}>{p.item}</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 22, color: C.text, letterSpacing: 1 }}>${p.spend.toFixed(2)}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim }}>{p.qty} orders</p></div></div>))}</div></div>)}
      {/* Active Shipments */}
      {activeShipments && activeShipments.length > 0 && (<div style={{ ...cardStyle, padding: 0, marginBottom: 24, overflow: "hidden" }}><div style={{ padding: "14px 20px", borderBottom: `1px solid ${C.border}`, display: "flex", alignItems: "center", gap: 8 }}><div style={{ color: "#4fc3f7" }}>{Ico.truck}</div><h3 style={{ ...sectionTitle, marginBottom: 0 }}>Active Shipments</h3><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: "#4fc3f7", background: "rgba(79,195,247,0.1)", padding: "2px 8px", borderRadius: 4, fontWeight: 700 }}>{activeShipments.length}</span></div>{activeShipments.slice(0, 6).map((o, i) => { const tUrl = trackingUrl(o.carrier, o.tracking_number); const etaLabel = (() => { if (!o.estimated_delivery) return null; const eta = new Date(o.estimated_delivery + "T23:59:59"); const dLeft = Math.ceil((eta - new Date()) / 86400000); if (dLeft <= 0) return "Arriving Today"; if (dLeft === 1) return "Arrives Tomorrow"; const dn = eta.toLocaleDateString("en-US", { weekday: "long" }); return dLeft <= 6 ? `Arrives ${dn}` : `Arrives in ${dLeft}d`; })(); return (<div key={o.id || i} style={{ padding: "12px 20px", borderBottom: `1px solid rgba(26,26,26,0.5)`, display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }}><RetailerDot name={o.retailer} size={8}/><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.text, fontWeight: 500, flex: "1 1 200px", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{o.item}</span><ShippingProgress status={o.status}/><StatusBadge status={o.status}/>{etaLabel && <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, fontWeight: 700, color: etaLabel.includes("Today") ? C.success : C.chrome }}>{etaLabel}</span>}{o.tracking_number && <div style={{ display: "flex", alignItems: "center", gap: 4 }}>{tUrl ? <a href={tUrl} target="_blank" rel="noopener noreferrer" style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: "#4fc3f7", textDecoration: "none" }}>{o.tracking_number.slice(-8)} {Ico.extLink}</a> : <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim }}>{o.tracking_number.slice(-8)}</span>}<CopyBtn text={o.tracking_number}/></div>}</div>); })}{activeShipments.length > 6 && <div style={{ padding: "10px 20px", textAlign: "center" }}><button onClick={() => setPage("tracking")} style={btnGhost}>View all {activeShipments.length} shipments {Ico.arrow}</button></div>}</div>)}
      {/* Retailer + Monthly */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 12, marginBottom: 24 }}><div style={cardStyle}><h3 style={sectionTitle}>By Retailer</h3>{retailers.map(r => { const count = stats.byRetailer[r]; const pct = Math.round((count / stats.totalOrders) * 100); const spend = stats.retailerSpend?.[r]; return (<div key={r} style={{ marginBottom: 12 }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 4 }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><RetailerDot name={r}/><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.text }}>{r}</span></div><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textMid }}>{count}{spend ? ` / $${spend.toFixed(0)}` : ""}</span></div><div style={{ height: 5, background: "rgba(200,200,200,0.04)", borderRadius: 3, overflow: "hidden" }}><div style={{ height: "100%", width: `${pct}%`, background: retailerCol[r] || C.chrome, borderRadius: 3 }}/></div></div>); })}</div><div style={cardStyle}><h3 style={sectionTitle}>Monthly Spend</h3>{stats.monthlySpend && Object.entries(stats.monthlySpend).reverse().map(([month, amount]) => { const maxS = Math.max(...Object.values(stats.monthlySpend), 1); const pct = Math.round((amount / maxS) * 100); const label = new Date(month + "-01").toLocaleDateString("en-US", { month: "short", year: "numeric" }); return (<div key={month} style={{ marginBottom: 10 }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 3 }}><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.textMid }}>{label}</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text }}>${amount.toFixed(2)}</span></div><div style={{ height: 5, background: "rgba(200,200,200,0.04)", borderRadius: 3, overflow: "hidden" }}><div style={{ height: "100%", width: `${pct}%`, background: C.chrome, borderRadius: 3 }}/></div></div>); })}</div></div>
      {/* Recent Orders */}
      <div style={{ ...cardStyle, padding: 0, overflow: "hidden" }}><div style={{ padding: "14px 20px", borderBottom: `1px solid ${C.border}`, display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><h3 style={{ ...sectionTitle, marginBottom: 0 }}>Recent Orders</h3><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, background: "rgba(200,200,200,0.04)", padding: "2px 8px", borderRadius: 4 }}>{stats.totalOrders}</span></div><div style={{ display: "flex", gap: 6 }}><button onClick={() => exportCSV(allOrders || orders)} style={btnGhost}>{Ico.download} Export</button><button onClick={() => setPage("tracking")} style={btnGhost}>View All {Ico.arrow}</button></div></div><div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 700 }}><thead><tr>{["Retailer","Item","Order #","Date","Status","Carrier","Total"].map(h => (<th key={h} style={{ padding: "10px 16px", textAlign: "left", fontFamily: "'DM Mono',monospace", fontSize: 9, fontWeight: 600, color: C.textDim, letterSpacing: 1.5, textTransform: "uppercase", borderBottom: `1px solid ${C.border}` }}>{h}</th>))}</tr></thead><tbody>{orders.slice(0, 10).map((o, i) => (<tr key={o.id || i} style={{ borderBottom: `1px solid rgba(26,26,26,0.5)` }} onMouseEnter={e => e.currentTarget.style.background = "rgba(255,255,255,0.015)"} onMouseLeave={e => e.currentTarget.style.background = "transparent"}><td style={{ padding: "11px 16px" }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><RetailerDot name={o.retailer}/><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.text, fontWeight: 500 }}>{o.retailer}</span></div></td><td style={{ padding: "11px 16px", fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.textMid, maxWidth: 200, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{o.item}</td><td style={{ padding: "11px 16px" }}>{o.order_number ? <div style={{ display: "flex", alignItems: "center", gap: 4 }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim }}>{o.order_number}</span><CopyBtn text={o.order_number}/></div> : <span style={{ color: C.textDim }}>-</span>}</td><td style={{ padding: "11px 16px", fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>{o.order_date || ""}</td><td style={{ padding: "11px 16px" }}><StatusBadge status={o.status}/></td><td style={{ padding: "11px 16px", fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim }}>{o.carrier || "-"}</td><td style={{ padding: "11px 16px", fontFamily: "'DM Mono',monospace", fontSize: 13, color: C.text, fontWeight: 600 }}>{o.total != null ? `$${Number(o.total).toFixed(2)}` : ""}</td></tr>))}</tbody></table></div></div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   TRACKING PAGE
   ═══════════════════════════════════════════════════════════════ */
function TrackingPage({ data, loading, setPage }) {
  const [filter, setFilter] = useState("all"); const [retailerFilter, setRetailerFilter] = useState("all"); const [search, setSearch] = useState(""); const [expanded, setExpanded] = useState(null);
  if (loading) return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "60vh" }}><Spinner /></div>;
  if (!data?.allOrders?.length) return <EmptyState icon={Ico.tracking} title="No orders to track" desc="Run a scan from the Dashboard to start tracking." />;
  const orders = data.allOrders;
  const inTransit = orders.filter(o => o.status === "Shipped" || o.status === "Out for Delivery" || o.status === "In Transit");
  const delivered = orders.filter(o => o.status === "Delivered");
  const late = orders.filter(o => o.estimated_delivery && o.status !== "Delivered" && new Date(o.estimated_delivery) < new Date());
  const carriers = [...new Set(orders.filter(o => o.carrier).map(o => o.carrier))];
  const statuses = ["all","In Transit","Out for Delivery","Delivered","Confirmed","Cancelled","Late"];
  const retailers = ["all", ...new Set(orders.map(o => o.retailer))];
  const arrivingToday = orders.filter(o => o.estimated_delivery === new Date().toISOString().split("T")[0] && o.status !== "Delivered").length;
  const arrivingTomorrow = orders.filter(o => { const tom = new Date(); tom.setDate(tom.getDate() + 1); return o.estimated_delivery === tom.toISOString().split("T")[0] && o.status !== "Delivered"; }).length;
  const filtered = orders.filter(o => {
    if (filter === "In Transit" && o.status !== "Shipped" && o.status !== "In Transit") return false;
    else if (filter === "Late") { if (!o.estimated_delivery || o.status === "Delivered") return false; if (new Date(o.estimated_delivery) >= new Date()) return false; }
    else if (filter !== "all" && o.status !== filter) return false;
    if (retailerFilter !== "all" && o.retailer !== retailerFilter) return false;
    if (search) { const q = search.toLowerCase(); if (!(o.item||"").toLowerCase().includes(q) && !(o.order_number||"").toLowerCase().includes(q) && !(o.tracking_number||"").toLowerCase().includes(q) && !(o.carrier||"").toLowerCase().includes(q)) return false; }
    return true;
  });
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 12, marginBottom: 20 }}><div><h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, letterSpacing: 3 }}>TRACKING</h1><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>{orders.filter(o => o.tracking_number).length} packages with tracking &middot; {inTransit.length} in transit &middot; {delivered.length} delivered</p></div><button onClick={() => exportCSV(filtered)} style={btnSecondary}>{Ico.download} Export</button></div>
      <HeroBanner><div style={{ display: "grid", gridTemplateColumns: "1.2fr 1fr 1fr 1fr", gap: 20, alignItems: "center" }}><div><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 4 }}>In Transit</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 40, color: "#4fc3f7", lineHeight: 1 }}>{inTransit.length}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginTop: 4 }}>{arrivingToday} today &middot; {arrivingTomorrow} tomorrow{late.length > 0 ? ` \u00B7 ${late.length} late` : ""}</p></div><div style={{ borderLeft: `1px solid ${C.border}`, paddingLeft: 20 }}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 4 }}>Delivered</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.success, lineHeight: 1 }}>{delivered.length}</p></div><div style={{ borderLeft: `1px solid ${C.border}`, paddingLeft: 20 }}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 4 }}>Late</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: late.length > 0 ? C.error : C.textDim, lineHeight: 1 }}>{late.length}</p></div><div style={{ borderLeft: `1px solid ${C.border}`, paddingLeft: 20 }}><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 4 }}>Carriers</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, lineHeight: 1 }}>{carriers.length}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginTop: 2 }}>{carriers.join(" \u00B7 ")}</p></div></div></HeroBanner>
      <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginBottom: 12 }}>{statuses.map(s => { let count; if (s === "all") count = orders.length; else if (s === "In Transit") count = inTransit.length; else if (s === "Late") count = late.length; else count = orders.filter(o => o.status === s).length; if (count === 0 && s !== "all") return null; return <button key={s} onClick={() => setFilter(s)} style={{ background: filter === s ? "rgba(200,200,200,0.08)" : "transparent", border: `1px solid ${filter === s ? C.borderHov : C.border}`, borderRadius: 6, padding: "6px 12px", fontFamily: "'DM Sans',sans-serif", fontSize: 11, fontWeight: filter === s ? 600 : 400, color: filter === s ? C.text : C.textMid, cursor: "pointer" }}>{s === "all" ? "All" : s} <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, marginLeft: 2 }}>{count}</span></button>; })}</div>
      <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", marginBottom: 20 }}><select value={retailerFilter} onChange={e => setRetailerFilter(e.target.value)} style={{ ...inputBase, width: "auto", padding: "7px 12px", fontSize: 12 }}>{retailers.map(r => <option key={r} value={r}>{r === "all" ? "All Retailers" : r}</option>)}</select><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search tracking, order #, product, carrier..." style={{ ...inputBase, flex: 1, minWidth: 200, padding: "8px 14px", fontSize: 12 }} onFocus={focusS} onBlur={blurS} /></div>
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>{filtered.slice(0, 50).map((o, i) => {
        const isExp = expanded === (o.id || i); let items = []; if (o.items_json) { try { items = JSON.parse(o.items_json); } catch {} }
        const tUrl = trackingUrl(o.carrier, o.tracking_number);
        const etaLabel = (() => { if (!o.estimated_delivery || o.status === "Delivered") return null; const eta = new Date(o.estimated_delivery + "T23:59:59"); const dLeft = Math.ceil((eta - new Date()) / 86400000); if (dLeft <= 0) return "Arriving Today"; if (dLeft === 1) return "Arrives Tomorrow"; const dn = eta.toLocaleDateString("en-US", { weekday: "long" }); return dLeft <= 6 ? `Arrives ${dn}` : `Arrives in ${dLeft}d`; })();
        const isLate = o.estimated_delivery && o.status !== "Delivered" && new Date(o.estimated_delivery) < new Date();
        return (<div key={o.id || i} style={{ ...cardStyle, padding: 0, overflow: "hidden", cursor: "pointer", borderColor: isLate ? "rgba(255,82,82,0.2)" : C.border }} onClick={() => setExpanded(isExp ? null : (o.id || i))}>
          <div style={{ padding: "14px 20px", display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }}><RetailerDot name={o.retailer} size={8}/><div style={{ flex: "1 1 220px", minWidth: 0 }}><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.text, fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{o.item}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginTop: 2 }}>{o.order_number ? `#${o.order_number}` : ""} &middot; {o.retailer}{o.carrier ? ` \u00B7 ${o.carrier}` : ""} &middot; {o.order_date || ""}</p></div><ShippingProgress status={o.status}/><StatusBadge status={o.status}/>{etaLabel && <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, fontWeight: 700, color: etaLabel.includes("Today") ? C.success : isLate ? C.error : C.chrome }}>{isLate ? "Late" : etaLabel}</span>}{o.tracking_number && <div style={{ display: "flex", alignItems: "center", gap: 4 }}>{tUrl ? <a href={tUrl} target="_blank" rel="noopener noreferrer" onClick={e => e.stopPropagation()} style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: "#4fc3f7", textDecoration: "none" }}>{o.tracking_number.slice(-8)} {Ico.extLink}</a> : <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim }}>{o.tracking_number.slice(-8)}</span>}<CopyBtn text={o.tracking_number}/></div>}{o.total != null && <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 13, color: C.text, fontWeight: 600 }}>${Number(o.total).toFixed(2)}</span>}</div>
          {isExp && (<div style={{ padding: "0 20px 16px", borderTop: `1px solid ${C.border}`, paddingTop: 14 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 12 }}><div><span style={labelBase}>Order Number</span><div style={{ display: "flex", alignItems: "center", gap: 6 }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text }}>{o.order_number || "N/A"}</span>{o.order_number && <CopyBtn text={o.order_number}/>}</div></div><div><span style={labelBase}>Tracking</span><div style={{ display: "flex", alignItems: "center", gap: 6 }}>{tUrl ? <a href={tUrl} target="_blank" rel="noopener noreferrer" onClick={e => e.stopPropagation()} style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: "#4fc3f7", textDecoration: "none" }}>{o.tracking_number} {Ico.extLink}</a> : <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.textDim }}>{o.tracking_number || "N/A"}</span>}{o.tracking_number && <CopyBtn text={o.tracking_number}/>}</div></div><div><span style={labelBase}>Carrier</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text }}>{o.carrier || "Unknown"}</span></div>{o.estimated_delivery && <div><span style={labelBase}>ETA</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.success, fontWeight: 600 }}>{new Date(o.estimated_delivery + "T12:00:00").toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" })}</span></div>}{o.subtotal != null && <div><span style={labelBase}>Subtotal</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text }}>${Number(o.subtotal).toFixed(2)}</span></div>}{o.tax != null && <div><span style={labelBase}>Tax</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text }}>${Number(o.tax).toFixed(2)}</span></div>}{o.shipped_date && <div><span style={labelBase}>Shipped</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text }}>{o.shipped_date}</span></div>}{o.delivered_date && <div><span style={labelBase}>Delivered</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.success }}>{o.delivered_date}</span></div>}</div>{items.length > 1 && (<div style={{ marginTop: 12 }}><span style={labelBase}>Items</span>{items.map((it, j) => (<span key={j} style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.textMid, display: "block" }}>{it}</span>))}</div>)}</div>)}
        </div>);
      })}</div>
      {filtered.length > 50 && <p style={{ textAlign: "center", padding: 20, fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>Showing 50 of {filtered.length}</p>}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   UPCOMING DROPS PAGE
   ═══════════════════════════════════════════════════════════════ */
function DropsPage({ user }) {
  const [drops, setDrops] = useState([]); const [isAdmin, setIsAdmin] = useState(false); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState({ title: "", description: "", retailer: "", dropDate: "", dropTime: "", imageUrl: "", signupUrl: "" }); const [saving, setSaving] = useState(false);
  const loadDrops = useCallback(() => { fetch("/api/drops").then(r => r.json()).then(d => { setDrops(d.drops || []); setIsAdmin(d.isAdmin || false); setLoading(false); }).catch(() => setLoading(false)); }, []); useEffect(() => { loadDrops(); }, [loadDrops]);
  const openAdd = () => { setEditing(null); setForm({ title: "", description: "", retailer: "", dropDate: "", dropTime: "", imageUrl: "", signupUrl: "" }); setShowForm(true); };
  const openEdit = (drop) => { setEditing(drop); setForm({ title: drop.title, description: drop.description || "", retailer: drop.retailer || "", dropDate: drop.drop_date, dropTime: drop.drop_time || "", imageUrl: drop.image_url || "", signupUrl: drop.signup_url || "" }); setShowForm(true); };
  const saveDrop = async () => { setSaving(true); const body = { title: form.title, description: form.description, retailer: form.retailer, dropDate: form.dropDate, dropTime: form.dropTime, imageUrl: form.imageUrl, signupUrl: form.signupUrl }; if (editing) body.id = editing.id; const res = await fetch("/api/drops", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (res.ok) { setShowForm(false); loadDrops(); } setSaving(false); };
  const deleteDrop = async (id) => { if (!confirm("Delete this drop?")) return; await fetch("/api/drops", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); loadDrops(); };
  function getCountdown(dateStr, timeStr) { const dt = new Date(`${dateStr}T${timeStr || "00:00"}:00`); const diff = dt - new Date(); if (diff <= 0) return null; const days = Math.floor(diff / 86400000); const hrs = Math.floor((diff % 86400000) / 3600000); const mins = Math.floor((diff % 3600000) / 60000); if (days > 0) return `${days}d ${hrs}h`; if (hrs > 0) return `${hrs}h ${mins}m`; return `${mins}m`; }
  if (loading) return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "60vh" }}><Spinner /></div>;
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}><div><h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, letterSpacing: 3 }}>UPCOMING DROPS</h1><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>{drops.length} scheduled</p></div>{isAdmin && <button onClick={openAdd} style={btnPrimary}>{Ico.plus} Add Drop</button>}</div>
      {showForm && isAdmin && (<div style={{ ...cardStyle, marginBottom: 24, border: `1px solid ${C.borderHov}` }}><h3 style={{ ...sectionTitle, marginBottom: 16 }}>{editing ? "Edit Drop" : "Schedule New Drop"}</h3><div style={{ display: "grid", gap: 12 }}><div><label style={labelBase}>Product Title *</label><input value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} placeholder="Prismatic Evolutions ETB" style={inputBase} onFocus={focusS} onBlur={blurS}/></div><div><label style={labelBase}>Description</label><input value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} style={inputBase} onFocus={focusS} onBlur={blurS}/></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 }}><div><label style={labelBase}>Retailer</label><select value={form.retailer} onChange={e => setForm(f => ({ ...f, retailer: e.target.value }))} style={inputBase}><option value="">Select</option><option>Target</option><option>Walmart</option><option>Pokemon Center</option></select></div><div><label style={labelBase}>Drop Date *</label><input type="date" value={form.dropDate} onChange={e => setForm(f => ({ ...f, dropDate: e.target.value }))} style={inputBase}/></div><div><label style={labelBase}>Drop Time</label><input type="time" value={form.dropTime} onChange={e => setForm(f => ({ ...f, dropTime: e.target.value }))} style={inputBase}/></div></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}><div><label style={labelBase}>Image URL</label><input value={form.imageUrl} onChange={e => setForm(f => ({ ...f, imageUrl: e.target.value }))} style={inputBase}/></div><div><label style={labelBase}>Sign-up Link</label><input value={form.signupUrl} onChange={e => setForm(f => ({ ...f, signupUrl: e.target.value }))} style={inputBase}/></div></div><div style={{ display: "flex", gap: 8 }}><button onClick={saveDrop} disabled={saving || !form.title || !form.dropDate} style={{ ...btnPrimary, opacity: (saving || !form.title || !form.dropDate) ? 0.5 : 1 }}>{saving ? "Saving..." : editing ? "Update" : "Schedule"}</button><button onClick={() => setShowForm(false)} style={btnSecondary}>Cancel</button></div></div></div>)}
      {drops.length === 0 ? <EmptyState icon={Ico.calendar} title="No upcoming drops" desc="Check back soon." /> : (<div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: 12 }}>{drops.map(drop => { const countdown = getCountdown(drop.drop_date, drop.drop_time); const isToday = drop.drop_date === new Date().toISOString().split("T")[0]; return (<div key={drop.id} style={{ ...cardStyle, padding: 0, overflow: "hidden", border: isToday ? "1px solid rgba(0,230,118,0.25)" : `1px solid ${C.border}` }}>{drop.image_url && <div style={{ width: "100%", height: 170, background: `url(${drop.image_url}) center/cover no-repeat`, borderBottom: `1px solid ${C.border}` }}/>}<div style={{ padding: "16px 20px" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 }}><h3 style={{ fontFamily: "'Syne',sans-serif", fontSize: 16, fontWeight: 700, color: C.text, flex: 1 }}>{drop.title}</h3>{countdown && <div style={{ display: "flex", alignItems: "center", gap: 4, background: isToday ? "rgba(0,230,118,0.08)" : "rgba(200,200,200,0.04)", padding: "4px 10px", borderRadius: 5, flexShrink: 0, marginLeft: 8, border: `1px solid ${isToday ? "rgba(0,230,118,0.15)" : C.border}` }}><div style={{ color: isToday ? C.success : C.chrome }}>{Ico.clock}</div><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, fontWeight: 700, color: isToday ? C.success : C.chrome }}>{countdown}</span></div>}</div>{drop.description && <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.textMid, marginBottom: 10, lineHeight: 1.5 }}>{drop.description}</p>}<div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap", marginBottom: 10 }}>{drop.retailer && <div style={{ display: "flex", alignItems: "center", gap: 5 }}><RetailerDot name={drop.retailer}/><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.textMid }}>{drop.retailer}</span></div>}<span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim }}>{new Date(drop.drop_date + "T12:00:00").toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" })}{drop.drop_time ? ` at ${drop.drop_time}` : ""}</span></div><div style={{ display: "flex", gap: 6 }}>{drop.signup_url && <a href={drop.signup_url} target="_blank" rel="noopener noreferrer" onClick={e => e.stopPropagation()} style={{ ...btnPrimary, fontSize: 11, padding: "7px 16px", textDecoration: "none" }}>Sign Up {Ico.extLink}</a>}{isAdmin && <><button onClick={() => openEdit(drop)} style={{ ...btnGhost, border: `1px solid ${C.border}`, borderRadius: 6 }}>{Ico.edit}</button><button onClick={() => deleteDrop(drop.id)} style={{ ...btnGhost, color: C.error, border: "1px solid rgba(255,82,82,0.15)", borderRadius: 6 }}>{Ico.trash}</button></>}</div></div></div>); })}</div>)}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   EMAIL ACCOUNTS PAGE
   ═══════════════════════════════════════════════════════════════ */
const providers = [
  { key: "gmail", label: "Gmail", server: "imap.gmail.com", hint: "Use an App Password with 2FA enabled", icon: "G" },
  { key: "icloud", label: "iCloud", server: "imap.mail.me.com", hint: "Use an App-Specific Password from appleid.apple.com", icon: "A" },
  { key: "outlook", label: "Outlook", server: "outlook.office365.com", hint: "Use your password or an app password", icon: "O" },
  { key: "yahoo", label: "Yahoo", server: "imap.mail.yahoo.com", hint: "Use an App Password from Yahoo Account Security", icon: "Y" },
  { key: "custom", label: "Custom IMAP", server: "", hint: "Enter your IMAP server manually", icon: "@" },
];

function EmailAccountsPage({ user, scanResult }) {
  const [accounts, setAccounts] = useState([]); const [loading, setLoading] = useState(true); const [showAdd, setShowAdd] = useState(false);
  const [addForm, setAddForm] = useState({ provider: "gmail", email: "", password: "", imapServer: "imap.gmail.com" }); const [adding, setAdding] = useState(false); const [addError, setAddError] = useState(null);
  useEffect(() => { fetch("/api/emails").then(r => r.json()).then(d => { setAccounts(d.accounts || []); setLoading(false); }).catch(() => setLoading(false)); }, []);
  const handleAddAccount = async () => { setAdding(true); setAddError(null); const prov = providers.find(p => p.key === addForm.provider); try { const res = await fetch("/api/emails", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label: prov?.label || addForm.provider, provider: addForm.provider, email: addForm.email, imapServer: addForm.imapServer, password: addForm.password }) }); const d = await res.json(); if (!res.ok) { setAddError(d.error); } else { setAccounts(p => [...p, d.account]); setShowAdd(false); setAddForm({ provider: "gmail", email: "", password: "", imapServer: "imap.gmail.com" }); } } catch { setAddError("Network error"); } setAdding(false); };
  const removeAccount = async (id) => { if (!confirm("Remove this email account?")) return; await fetch("/api/emails", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); setAccounts(p => p.filter(a => a.id !== id)); };
  if (loading) return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "60vh" }}><Spinner /></div>;
  const currentProv = providers.find(p => p.key === addForm.provider);
  const liveCount = accounts.filter(a => a.status === "active").length;
  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20 }}><div><h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, letterSpacing: 3 }}>ACCOUNTS</h1><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>{accounts.length} accounts &middot; <span style={{ color: C.success }}>{liveCount} live</span></p></div><button onClick={() => setShowAdd(!showAdd)} style={showAdd ? btnSecondary : btnPrimary}>{showAdd ? "Cancel" : <>{Ico.plus} Connect Account</>}</button></div>
      <HeroBanner><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.chromeDim, letterSpacing: 2, textTransform: "uppercase", marginBottom: 4 }}>Email Sync</p><p style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 40, color: C.text, lineHeight: 1 }}>{accounts.length} <span style={{ fontSize: 20, color: C.chromeDim }}>accounts</span></p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginTop: 4 }}>{liveCount} live &middot; run a scan from Dashboard to sync</p></div></div></HeroBanner>
      {showAdd && (<div style={{ ...cardStyle, marginBottom: 20, border: `1px solid ${C.borderHov}` }}><h3 style={{ ...sectionTitle, marginBottom: 14 }}>Connect New Account</h3><div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 16 }}>{providers.map(p => (<button key={p.key} onClick={() => setAddForm(f => ({ ...f, provider: p.key, imapServer: p.server || f.imapServer }))} style={{ display: "flex", alignItems: "center", gap: 6, background: addForm.provider === p.key ? "rgba(200,200,200,0.08)" : "transparent", border: `1px solid ${addForm.provider === p.key ? C.borderHov : C.border}`, borderRadius: 7, padding: "8px 14px", fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: addForm.provider === p.key ? C.text : C.textMid, cursor: "pointer" }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, fontWeight: 700, width: 18, textAlign: "center" }}>{p.icon}</span>{p.label}</button>))}</div><div style={{ display: "grid", gap: 12 }}><div><label style={labelBase}>Email Address</label><input value={addForm.email} onChange={e => setAddForm(f => ({ ...f, email: e.target.value }))} placeholder="you@gmail.com" style={inputBase} onFocus={focusS} onBlur={blurS}/></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}><div><label style={labelBase}>App Password</label><input type="password" value={addForm.password} onChange={e => setAddForm(f => ({ ...f, password: e.target.value }))} style={inputBase}/></div><div><label style={labelBase}>IMAP Server</label>{addForm.provider === "custom" ? <input value={addForm.imapServer} onChange={e => setAddForm(f => ({ ...f, imapServer: e.target.value }))} style={inputBase}/> : <div style={{ ...inputBase, color: C.textMid, background: "rgba(200,200,200,0.02)" }}>{addForm.imapServer}</div>}</div></div>{currentProv?.hint && <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 11, color: C.textDim, display: "flex", alignItems: "center", gap: 6 }}>{Ico.lock} {currentProv.hint}</p>}{addError && <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: "#ff6b6b" }}>{addError}</p>}<button onClick={handleAddAccount} disabled={adding || !addForm.email || !addForm.password} style={{ ...btnPrimary, opacity: (adding || !addForm.email || !addForm.password) ? 0.5 : 1 }}>{adding ? <><Spinner size={14} color={C.bg}/> Testing...</> : "Connect Account"}</button></div></div>)}
      {accounts.length === 0 && !showAdd ? <EmptyState icon={Ico.mail} title="No accounts connected" desc="Link an email to start scanning for orders." action={() => setShowAdd(true)} actionLabel="Connect Account" /> : (<div style={{ marginBottom: 24 }}><h3 style={{ ...sectionTitle, display: "flex", alignItems: "center", gap: 8 }}>Connected <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, background: "rgba(200,200,200,0.04)", padding: "2px 8px", borderRadius: 4, color: C.textDim }}>{accounts.length}</span></h3><div style={{ display: "flex", flexDirection: "column", gap: 6 }}>{accounts.map(acc => (<div key={acc.id} style={{ ...cardStyle, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 20px" }}><div style={{ display: "flex", alignItems: "center", gap: 14 }}><div style={{ width: 40, height: 40, borderRadius: 10, background: acc.status === "active" ? "rgba(0,230,118,0.05)" : "rgba(255,82,82,0.05)", border: `1px solid ${acc.status === "active" ? "rgba(0,230,118,0.12)" : "rgba(255,82,82,0.12)"}`, display: "flex", alignItems: "center", justifyContent: "center" }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 16, fontWeight: 700, color: acc.status === "active" ? C.success : C.error }}>{acc.provider?.charAt(0)?.toUpperCase() || "@"}</span></div><div><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.text, fontWeight: 600 }}>{acc.email}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim }}>{acc.label}{acc.last_scanned ? ` \u00B7 Last: ${new Date(acc.last_scanned).toLocaleDateString()}` : ""}</p></div></div><div style={{ display: "flex", alignItems: "center", gap: 10 }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, fontWeight: 700, color: acc.status === "active" ? C.success : C.error, background: acc.status === "active" ? "rgba(0,230,118,0.08)" : "rgba(255,82,82,0.08)", padding: "3px 10px", borderRadius: 4, display: "flex", alignItems: "center", gap: 4 }}><div style={{ width: 5, height: 5, borderRadius: "50%", background: acc.status === "active" ? C.success : C.error, animation: acc.status === "active" ? "pulse 3s ease infinite" : "none" }}/>{acc.status === "active" ? "LIVE" : "ERROR"}</span><button onClick={() => removeAccount(acc.id)} style={{ background: "none", border: "none", color: C.textDim, cursor: "pointer", padding: 4 }}>{Ico.trash}</button></div></div>))}</div></div>)}
      {scanResult && !scanResult.error && (<div style={cardStyle}><h3 style={{ ...sectionTitle, display: "flex", alignItems: "center", gap: 8 }}>Last Sync <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.success, background: "rgba(0,230,118,0.08)", padding: "2px 8px", borderRadius: 4 }}>Complete</span></h3><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.textMid }}>{scanResult.count} orders found, {scanResult.updated || 0} updated.</p></div>)}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   INSIGHTS PAGE — Donut chart, breakdowns, top products
   ═══════════════════════════════════════════════════════════════ */
function InsightsPage({ data, loading }) {
  if (loading) return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "60vh" }}><Spinner /></div>;
  if (!data?.stats?.totalOrders) return <EmptyState icon={Ico.insights} title="No data yet" desc="Run a scan to populate your insights." />;
  const { stats, allOrders } = data;
  const retailers = Object.keys(stats.byRetailer);
  const statuses = Object.keys(stats.byStatus);
  const donutData = retailers.map(r => ({ label: r, value: stats.byRetailer[r], color: retailerCol[r] || C.chrome }));

  // All products aggregated
  const productMap = {}; (allOrders || []).forEach(o => { if (!o.item) return; const k = o.item; if (!productMap[k]) productMap[k] = { item: k, qty: 0, spend: 0, retailers: new Set() }; productMap[k].qty++; if (o.total) productMap[k].spend += Number(o.total); if (o.retailer) productMap[k].retailers.add(o.retailer); });
  const allProducts = Object.values(productMap).sort((a, b) => b.spend - a.spend);

  // Spend by status
  const spendByStatus = {}; (allOrders || []).forEach(o => { if (o.status && o.total) { spendByStatus[o.status] = (spendByStatus[o.status] || 0) + Number(o.total); } });

  return (
    <div>
      <div style={{ marginBottom: 20 }}><h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, letterSpacing: 3 }}>INSIGHTS</h1><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>{stats.totalOrders} orders &middot; ${Number(stats.totalSpend).toLocaleString(undefined, { minimumFractionDigits: 2 })} total spend</p></div>

      {/* Donut + status breakdown */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 12, marginBottom: 24 }}>
        <div style={cardStyle}>
          <h3 style={sectionTitle}>Retailer Breakdown</h3>
          <div style={{ display: "flex", alignItems: "center", gap: 24 }}>
            <DonutChart data={donutData} size={140} />
            <div style={{ flex: 1 }}>{donutData.map(d => (<div key={d.label} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 8 }}><div style={{ display: "flex", alignItems: "center", gap: 8 }}><div style={{ width: 10, height: 10, borderRadius: 3, background: d.color }}/><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.text }}>{d.label}</span></div><div style={{ textAlign: "right" }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text, fontWeight: 600 }}>{d.value}</span>{stats.retailerSpend?.[d.label] != null && <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginLeft: 6 }}>${stats.retailerSpend[d.label].toFixed(0)}</span>}</div></div>))}</div>
          </div>
        </div>
        <div style={cardStyle}>
          <h3 style={sectionTitle}>By Status</h3>
          {statuses.sort((a, b) => stats.byStatus[b] - stats.byStatus[a]).map(s => { const count = stats.byStatus[s]; const pct = Math.round((count / stats.totalOrders) * 100); const col = statusCol[s] || C.textMid; return (<div key={s} style={{ marginBottom: 10 }}><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 3 }}><div style={{ display: "flex", alignItems: "center", gap: 6 }}><div style={{ width: 6, height: 6, borderRadius: "50%", background: col }}/><span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.text }}>{s}</span></div><div><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.text, fontWeight: 600 }}>{count}</span><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginLeft: 6 }}>{pct}%</span>{spendByStatus[s] && <span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim, marginLeft: 6 }}>${spendByStatus[s].toFixed(0)}</span>}</div></div><div style={{ height: 4, background: "rgba(200,200,200,0.04)", borderRadius: 2, overflow: "hidden" }}><div style={{ height: "100%", width: `${pct}%`, background: col, borderRadius: 2 }}/></div></div>); })}
        </div>
      </div>

      {/* All products */}
      <div style={{ ...cardStyle, padding: 0, overflow: "hidden" }}>
        <div style={{ padding: "14px 20px", borderBottom: `1px solid ${C.border}`, display: "flex", justifyContent: "space-between", alignItems: "center" }}><h3 style={{ ...sectionTitle, marginBottom: 0 }}>All Products</h3><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim }}>{allProducts.length} unique</span></div>
        <div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 500 }}><thead><tr>{["#","Product","Orders","Spend","Retailers"].map(h => (<th key={h} style={{ padding: "10px 16px", textAlign: "left", fontFamily: "'DM Mono',monospace", fontSize: 9, fontWeight: 600, color: C.textDim, letterSpacing: 1.5, textTransform: "uppercase", borderBottom: `1px solid ${C.border}` }}>{h}</th>))}</tr></thead><tbody>{allProducts.slice(0, 25).map((p, i) => (<tr key={i} style={{ borderBottom: `1px solid rgba(26,26,26,0.5)` }}><td style={{ padding: "10px 16px" }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 10, fontWeight: 700, color: i < 3 ? C.warn : C.textDim }}>#{i + 1}</span></td><td style={{ padding: "10px 16px", fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.text, maxWidth: 280, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{p.item}</td><td style={{ padding: "10px 16px", fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text }}>{p.qty}</td><td style={{ padding: "10px 16px", fontFamily: "'DM Mono',monospace", fontSize: 12, color: C.text, fontWeight: 600 }}>${p.spend.toFixed(2)}</td><td style={{ padding: "10px 16px" }}><div style={{ display: "flex", gap: 4 }}>{[...p.retailers].map(r => <RetailerDot key={r} name={r} size={6}/>)}</div></td></tr>))}</tbody></table></div>
        {allProducts.length > 25 && <p style={{ textAlign: "center", padding: 14, fontFamily: "'DM Mono',monospace", fontSize: 10, color: C.textDim }}>Showing top 25 of {allProducts.length}</p>}
      </div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   SETTINGS PAGE — Webhook, notifications, send test
   ═══════════════════════════════════════════════════════════════ */
function SettingsPage({ user }) {
  const [settings, setSettings] = useState({ discord_webhook_url: "", notify_new_order: true, notify_shipped: true, notify_delivered: true, notify_cancelled: true }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [testResult, setTestResult] = useState(null); const [testing, setTesting] = useState(false);
  useEffect(() => { fetch("/api/settings").then(r => r.json()).then(d => { if (d.settings) setSettings(s => ({ ...s, ...d.settings })); setLoading(false); }).catch(() => setLoading(false)); }, []);
  const saveSettings = async () => { setSaving(true); setSaved(false); try { const res = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); if (res.ok) { setSaved(true); setTimeout(() => setSaved(false), 3000); } } catch {} setSaving(false); };
  const sendTest = async () => { if (!settings.discord_webhook_url) return; setTesting(true); setTestResult(null); try { const res = await fetch(settings.discord_webhook_url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content: null, embeds: [{ title: "LIVEFAST ACO - Test Notification", description: "Your webhook is working.", color: 2303786, footer: { text: "LIVEFAST ACO" }, timestamp: new Date().toISOString() }] }) }); setTestResult(res.ok ? "success" : "failed"); } catch { setTestResult("failed"); } setTesting(false); setTimeout(() => setTestResult(null), 4000); };
  if (loading) return <div style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "60vh" }}><Spinner /></div>;
  return (
    <div>
      <div style={{ marginBottom: 24 }}><h1 style={{ fontFamily: "'Bebas Neue',sans-serif", fontSize: 32, color: C.text, letterSpacing: 3 }}>SETTINGS</h1><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>Configure notifications and preferences</p></div>
      {/* Webhook */}
      <div style={{ ...cardStyle, marginBottom: 16 }}>
        <h3 style={sectionTitle}>Discord Webhook</h3>
        <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.textMid, marginBottom: 14 }}>Get notified in Discord when orders are checked out, shipped, or delivered.</p>
        <div style={{ marginBottom: 12 }}><label style={labelBase}>Webhook URL</label><div style={{ display: "flex", gap: 8 }}><input value={settings.discord_webhook_url || ""} onChange={e => setSettings(s => ({ ...s, discord_webhook_url: e.target.value }))} placeholder="https://discord.com/api/webhooks/..." style={{ ...inputBase, flex: 1 }} onFocus={focusS} onBlur={blurS}/><button onClick={sendTest} disabled={testing || !settings.discord_webhook_url} style={{ ...btnSecondary, opacity: (testing || !settings.discord_webhook_url) ? 0.5 : 1, flexShrink: 0 }}>{testing ? <Spinner size={14}/> : Ico.send} Test</button></div></div>
        {testResult && <p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: testResult === "success" ? C.success : C.error, marginBottom: 8 }}>{testResult === "success" ? "Test sent successfully." : "Failed to send test."}</p>}
      </div>
      {/* Notifications */}
      <div style={{ ...cardStyle, marginBottom: 16 }}>
        <h3 style={sectionTitle}>Notifications</h3>
        {[{ key: "notify_new_order", label: "Checkout Confirmations", desc: "When a new order is placed" },{ key: "notify_shipped", label: "Shipping Updates", desc: "When an order ships or tracking updates" },{ key: "notify_delivered", label: "Delivery Confirmations", desc: "When a package is delivered" },{ key: "notify_cancelled", label: "Cancellations", desc: "When an order is cancelled or refunded" }].map(n => (<div key={n.key} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 0", borderBottom: `1px solid ${C.border}` }}><div><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 13, color: C.text, fontWeight: 500 }}>{n.label}</p><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 11, color: C.textDim }}>{n.desc}</p></div><button onClick={() => setSettings(s => ({ ...s, [n.key]: !s[n.key] }))} style={{ width: 44, height: 24, borderRadius: 12, border: "none", background: settings[n.key] ? C.success : "rgba(200,200,200,0.1)", cursor: "pointer", position: "relative", transition: "background 0.2s" }}><div style={{ width: 18, height: 18, borderRadius: 9, background: "#fff", position: "absolute", top: 3, left: settings[n.key] ? 23 : 3, transition: "left 0.2s" }}/></button></div>))}
      </div>
      {/* Account info */}
      <div style={{ ...cardStyle, marginBottom: 16 }}>
        <h3 style={sectionTitle}>Linked Account</h3>
        <div style={{ display: "flex", alignItems: "center", gap: 14 }}><div style={{ width: 48, height: 48, borderRadius: 12, background: "rgba(88,101,242,0.1)", display: "flex", alignItems: "center", justifyContent: "center" }}><span style={{ fontFamily: "'DM Mono',monospace", fontSize: 18, color: C.discord, fontWeight: 700 }}>{user?.username?.charAt(0)?.toUpperCase() || "?"}</span></div><div><p style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 15, color: C.text, fontWeight: 600 }}>{user?.username}</p><p style={{ fontFamily: "'DM Mono',monospace", fontSize: 11, color: C.textDim }}>Discord ID: {user?.id}</p></div></div>
      </div>
      {/* Save */}
      <div style={{ display: "flex", gap: 8, alignItems: "center" }}><button onClick={saveSettings} disabled={saving} style={{ ...btnPrimary, opacity: saving ? 0.6 : 1 }}>{saving ? "Saving..." : saved ? <>{Ico.check} Saved</> : "Save Settings"}</button>{saved && <span style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: C.success }}>Settings saved</span>}</div>
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════
   MAIN APP — Data fetching, routing, layout
   ═══════════════════════════════════════════════════════════════ */
export default function App({ user, error }) {
  const [page, setPage] = useState("dashboard");
  const [collapsed, setCollapsed] = useState(false);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [scanning, setScanning] = useState(false);
  const [scanResult, setScanResult] = useState(null);

  const loadData = useCallback(async () => {
    try {
      const res = await fetch("/api/dashboard");
      if (res.ok) { const d = await res.json(); setData(d); }
    } catch {}
    setLoading(false);
  }, []);

  useEffect(() => { if (user) loadData(); else setLoading(false); }, [user, loadData]);

  const runScan = async () => {
    setScanning(true); setScanResult(null);
    try {
      const res = await fetch("/api/emails/scan", { method: "POST" });
      const d = await res.json();
      if (res.ok) { setScanResult({ count: d.totalOrders || 0, updated: d.updated || 0 }); loadData(); }
      else { setScanResult({ error: d.error || "Scan failed" }); }
    } catch { setScanResult({ error: "Network error" }); }
    setScanning(false);
  };

  if (!user) return (
    <>
      <Head>
        <title>LIVEFAST ACO</title>
        <meta name="description" content="Automated checkout operations for Pokemon TCG and collectibles" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Mono:wght@400;500&family=DM+Sans:wght@400;500;600;700&family=Syne:wght@600;700;800&display=swap" rel="stylesheet" />
      </Head>
      <LandingPage error={error} />
    </>
  );

  const sidebarW = collapsed ? 64 : 220;
  const inTransitCount = data?.activeShipments?.length || 0;

  return (
    <>
      <Head>
        <title>LIVEFAST ACO - Dashboard</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Mono:wght@400;500&family=DM+Sans:wght@400;500;600;700&family=Syne:wght@600;700;800&display=swap" rel="stylesheet" />
      </Head>
      <Sidebar page={page} setPage={setPage} user={user} collapsed={collapsed} setCollapsed={setCollapsed} inTransitCount={inTransitCount} />
      <main style={{ marginLeft: sidebarW, minHeight: "100vh", background: C.bg, padding: "28px 32px", transition: "margin-left 0.25s ease" }}>
        {page === "dashboard" && <DashboardPage setPage={setPage} data={data} loading={loading} runScan={runScan} scanning={scanning} scanResult={scanResult} setScanResult={setScanResult} />}
        {page === "tracking" && <TrackingPage data={data} loading={loading} setPage={setPage} />}
        {page === "drops" && <DropsPage user={user} />}
        {page === "emails" && <EmailAccountsPage user={user} scanResult={scanResult} />}
        {page === "insights" && <InsightsPage data={data} loading={loading} />}
        {page === "settings" && <SettingsPage user={user} />}
      </main>
    </>
  );
}

export async function getServerSideProps({ req, query }) {
  const { getSession } = require("../lib/session");
  const session = await getSession(req);
  return { props: { user: session?.user || null, error: query.error || null } };
}
// v4 deploy
